[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Jonathan Green <jonathan@razzard.com>"]
description = "Poetry plugin to set package version from SCM tag."
name = "poetry-scm-version"
packages = [
    { include = "poetry_scm_version", from = "src" }
]
version = "scm-version"

[tool.poetry.dependencies]
poetry = "^1.2.0a1"
python = "^3.7"
wrapt = "^1.13.3"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.17.0"

[tool.poetry.plugins."poetry.application.plugin"]
poetry-scm-version = "poetry_scm_version.plugin:ScmPatchPlugin"

[tool.poetry.plugins."poetry.plugin"]
poetry-scm-version = "poetry_scm_version.plugin:ScmVersionPlugin"
