[tool.poetry]
name = "poetry-scm-version"
version = "scm-version"
#version = "0"
description = "Poetry plugin to set package version from SCM tag."
authors = ["Jonathan Green <jonathan@razzard.com>"]
packages = [
    { include = "poetry_scm_version", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.2.0a1"
wrapt = "^1.13.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.17.0"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."poetry.application.plugin"]
poetry-scm-version = "poetry_scm_version.plugin:ScmPatchPlugin"

[tool.poetry.plugins."poetry.plugin"]
poetry-scm-version = "poetry_scm_version.plugin:ScmVersionPlugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
