name: 'Poetry'
description: 'Install python poetry'

inputs:
  version:
    description: "Version of poetry to install"
    required: false
    default: "1.2.0a2"

outputs:
  version:
    description: "Installed version"
    value: ${{ steps.poetry-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - run: |
        curl -sSL https://install.python-poetry.org | python - --yes --version ${{ inputs.version }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    # Need to unset our version string to bootstrap our
    # own install, otherwise we can't install from source.
    - run: |
        sed -i 's/version = "scm"/version = "0"/g' pyproject.toml
        poetry plugin add $(pwd)
        git checkout pyproject.toml
      shell: bash

    - id: poetry-version
      run: echo "::set-output name=version::$(poetry --version)"
      shell: bash
